#  Note! All Resources which related to the same microservice must have the common label

apiVersion: apps/v1         # версия API Kubernetes для Deployment
kind: Deployment            # тип ресурса — Deployment (управляет Pod'ами)
metadata:
  name: just-fire-service-deployment   # simply the name of resource
  labels:                   # is need for it to be found by other resources (resources in k8s are objects, doing certain stuff)
    app: just-fire-service  # MUST BE COMMON FOR ALL RESOURCES RELATED TO THE SAME MICROSERVICE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: just-fire-service
  template:
    metadata:
      labels:
        app: just-fire-service
    spec:
      containers:
        - name: just-fire-service
          image: just-fire-microservice:latest # the name of the image you created by -> docker build -t just-fire-microservice:latest .
          imagePullPolicy: Never # download it from Dockerhub: never - it's for local development
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: just-fire-service-secrets


